export const SHELL_DEFAULT_LEFT_PANEL_WIDTH = 280;
export const SHELL_DEFAULT_RIGHT_PANEL_WIDTH = 320;
export const SHELL_DEFAULT_TIMELINE_PANEL_HEIGHT = 280;

export const SHELL_LEFT_PANEL_MIN_WIDTH = 220;
export const SHELL_LEFT_PANEL_MAX_FLOOR_WIDTH = 260;
export const SHELL_RIGHT_PANEL_MIN_WIDTH = 260;
export const SHELL_RIGHT_PANEL_MAX_FLOOR_WIDTH = 280;
export const SHELL_SIDE_PANEL_MAX_WIDTH = 520;
export const SHELL_CENTER_MIN_WIDTH = 420;
export const SHELL_TIMELINE_PANEL_MIN_HEIGHT = 220;
export const SHELL_TIMELINE_PANEL_MAX_HEIGHT = 480;
export const SHELL_MAIN_AREA_MIN_HEIGHT = 220;
