export const TIMELINE_DURATION_EDITOR_HEIGHT = 24;
export const TIMELINE_DURATION_EDITOR_INPUT_WIDTH = 14;
export const TIMELINE_GROUP_GAP_PX = 2;
export const TIMELINE_ITEM_ROW_HEIGHT = 24;
export const TIMELINE_PROPERTY_ROW_HEIGHT = 13;
